version: '3.7'

services:
  web:
    container_name: divisionly-api
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    ports:
      - 3000:3000
    restart: always
    environment:
      - RAILS_ENV=production
    depends_on:
      - db

  db:
    container_name: postgres
    image: postgres:12.8
    ports:
      - 5432:5432
    restart: always
    environment:
      POSTGRES_USER: divisionly-api
      POSTGRES_PASSWORD: divisionly-api
      POSTGRES_DB: divisionly-api
