default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  port: <%= ENV['DB_PORT_NUMBER'] %>
  username: <%= ENV['DB_USERNAME'] %>
  password: <%= ENV['DB_PASSWORD'] %>

development:
  <<: *default
  host: <%= ENV['DB_HOST_DEV'] %>
  database: <%= ENV['DB_NAME'] %>_dev

test:
  <<: *default
  host: <%= ENV['DB_HOST_TEST'] %>
  database: <%= ENV['DB_NAME'] %>_test

production:
  <<: *default
  host: <%= ENV['DB_HOST_PROD'] %>
  database: <%= ENV['DB_NAME'] %>_prod